### ISSUE TITLE
store.default.observe is not a function

### ISSUE THREAD

**Issue by strodoff** [aniddan/delux#3]
Hi )
we use delux since its release 
but  nearly a week ago after we updated delux we started receive:
store.default.observe is not a function error.
hope it helped

in addition i would recommend to add releases to this project, because currently i cannot load a previous release that i was certain about its performance.
(git tag -a "v0.0.0"  -m "release message").

**Comment by iddan** [comment]
10bff91b6656d500cfe42b0a92a4d1126247a35f
